spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/evator
    username: admin
    password: admin
    pool-size: 30
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

liquibase:
  change-log: classpath:liquibase-changeLog.xml