spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/evator
    username: admin
    password: admin
    pool-size: 30
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false